// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8tlG1sS4j0lP0Co58c4xemq0N72yUEAY',
    appId: '1:166861597203:web:b23798fe9defd017456de6',
    messagingSenderId: '166861597203',
    projectId: 'tugasakhir-68b31',
    authDomain: 'tugasakhir-68b31.firebaseapp.com',
    storageBucket: 'tugasakhir-68b31.appspot.com',
    measurementId: 'G-F9LDR2B04R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnOO9_uUR0drx06xn5nWOh4b6d0Y7x9bA',
    appId: '1:166861597203:android:cc514a974f030f68456de6',
    messagingSenderId: '166861597203',
    projectId: 'tugasakhir-68b31',
    storageBucket: 'tugasakhir-68b31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKKwf4zsKACkuhBZYyUgUED9WTB89rDeg',
    appId: '1:166861597203:ios:d1fa6ad85d7b43b4456de6',
    messagingSenderId: '166861597203',
    projectId: 'tugasakhir-68b31',
    storageBucket: 'tugasakhir-68b31.appspot.com',
    iosClientId: '166861597203-394do97s2bnvns02qkr5q51f3hpjkaer.apps.googleusercontent.com',
    iosBundleId: 'com.example.tes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKKwf4zsKACkuhBZYyUgUED9WTB89rDeg',
    appId: '1:166861597203:ios:d1fa6ad85d7b43b4456de6',
    messagingSenderId: '166861597203',
    projectId: 'tugasakhir-68b31',
    storageBucket: 'tugasakhir-68b31.appspot.com',
    iosClientId: '166861597203-394do97s2bnvns02qkr5q51f3hpjkaer.apps.googleusercontent.com',
    iosBundleId: 'com.example.tes',
  );
}
